name: smadan02
description: スマダン アプリ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # 画面構成で使用
  provider: ^6.1.1
  webview_flutter: ^4.0.7
  csv: ^6.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  file_picker: ^8.1.2
  video_player: ^2.9.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/butsudan/
    - assets/ihai/
    - assets/portrait/
    - assets/effect/
    - assets/news/
    - assets/people.csv
